# -*- coding: utf-8 -*-
"""ExerciciosIfElifElse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBc-oSTeBTl7-NOoLLCH9j0p9F2Jo4ZG

1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

numero1 = float(input('escolha um numero:'))
numero2 = float(input('escolha outro numero:'))
soma = numero1 + numero2
if soma >15:
  print(f'esse numero é maior do que 15, a sua soma foi {soma}')
else:
  print('a soma desse numero não é maior que 15')

"""Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.

"""

numero1 = float(input('escolha um numero:'))
if numero1 <0:
  print('esse numero é negativo')
elif numero1 ==0:
  print('esse numero é neutro')
else:
  print('esse numero é positivo')

"""3. Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = int(input('insira sua idade (De 1 a 100):'))
if idade >=18:
  print('você é maior de idade')
else:
  print('você é menor de idade')

"""4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

"""

temperatura = float(input('qual a tempratura atual? (apenas o numero)'))
if temperatura >=20 and temperatura <=25:
  print('a temperatura esta agradavel')
elif temperatura <=19:
  print('esta frio em')
else:
  print('esta quente em')

"""Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

numero1 = float(input('escolha um numero:'))
numero2 = float(input('escolha outro numero:'))
if numero1 == numero2:
  print('estes numeros são iguais!')
else:
  print('estes numeros não são iguais parça')

"""Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
 ACESSO PERMITIDO caso a senha seja válida.
 ACESSO NEGADO caso a senha seja inválida.
"""

senha = int(input('digite sua senha:'))
if senha == 1234:
  print('ACESSO PERMITIDO')
else:
  print('ACESSO NEGADO')

""" Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.

"""

nota1 = float(input('insira a primeira nota:'))
nota2 = float(input('insira a segunda nota:'))

media = (nota1 + nota2)/2

if media >=7:
  print(f'você foi aprovado! sua media foi{media:.2f}')
elif media >=5 and media <7:
  print(f'você ta de exame parça, boa sorte,sua media foi {media:.2f}')
else:
  print(f'você foi reprovado parça, tem nem exame, sua media foi {media:.2f}')

""" Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.

"""

time1 = float(input('por favor, informe a quantidade de gols que o primeiro time fez:'))
time2 = float(input('por favor, informe a quantidade de gols que o segundo time fez:'))
if time1>time2:
  print('o primeiro time ganhou paizão')
elif time1 == time2:
  print('ninguém ganhou paizão, foi um empate')
else:
  print('o segundo time que ganhou paizão')

""" Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

turno = str(input('em que turno vc estuda? insira m para matutino, v para vespetino e n para noturno: ')).lower()
if turno == 'm':
  print('Bom dia!')
elif turno == 'v':
  print('Boa Tarde!')
elif turno == 'n':
  print('Boa Noite!')
else:
  print('Valor Invalido!')

"""Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
 Criança para 0 até 11 anos;
 Adolescente para 12 até 18 anos;
 Jovem para 19 até 24 anos;
 Adulto para 25 até 40 anos;
 Meia Idade para 41 até 60 anos;
 Idoso acima de 60 anos.
"""

idade = int(input('insira sua idade e diremos sua faixa etaria: '))
if idade >=0 and idade <=11:
  print('você é criança parça')
elif idade >=12 and idade <=18:
  print('você é adolescente parça')
elif idade >=19 and idade <=24:
  print('você é jovem parça')
elif idade >=25 and idade <=40:
  print('você é adulto')
elif idade >=41 and idade <=60:
  print('você é de meia idade')
else:
  print('você é idoso, veião')

""". As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
 salários até R$ 280,00 (incluindo) : aumento de 20%
 salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
 salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
 salários de R$ 1500,00 em diante : aumento de 5%
Após o aumento ser realizado, informe na tela:
 o salário antes do reajuste;
 o percentual de aumento aplicado;
 o valor do aumento;
 o novo salário, após o aumento.
"""

salario = float(input('informe seu salário: '))
juros20 = salario*0.2
juros15 = salario*0.15
juros10 = salario*0.1
juros05 = salario*0.05

if salario <=280:
  print(f'seu salario era de {salario}, com o aumento de 20%, no valor de {salario*0.2:.2f},seu novo salario é de {salario + juros20}')
elif salario >=281 and salario <=700:
  print(f'seu salario era de {salario}, com o aumento de 15%, no valor de {salario*0.15:.2f},seu novo salario é de {salario + juros15}')
elif salario >=701 and salario <=1500:
  print(f'seu salario era de {salario}, com o aumento de 10%, no valor de {salario*0.1:.2f},seu novo salario é de {salario + juros10}')
else:
   print(f'seu salario era de {salario}, com o aumento de 5%, no valor de {salario*0.05:.2f},seu novo salario é de {salario + juros05}')

""". Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
"""

dia = int(input('insira um dia de 1 a 7: '))

if dia == 1:
  print('esse dia é um domingo')
elif dia == 2:
  print('esse dia é uma segunda')
elif dia == 3:
  print('esse dia é uma terça')
elif dia ==4:
  print('esse dia é uma quarta')
elif dia == 5:
  print('esse dia é uma quinta')
elif dia == 6:
  print('esse dia é uma sexta')
elif dia == 7 :
  print('esse dia é uma sábado')
else:
  print('DIA INVALIDO')

"""13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de
Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
do usuário, faça a devida conversão.

"""

temperatura = str(input('digite cf se quer converter de celsus para fahrenheit ou fc de fahrenheit para celsus: '))
graus = float(input('digite a temperatura: '))
if temperatura == 'cf':
  print(graus*1.8+32)
elif temperatura == 'fc':
  print((graus-32)* 5/9)
else:
  print('invalido')
# F = C x 1,8 + 32.
#°C = (°F - 32) × 5/9

"""Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
 Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
 Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
 Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
 Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).
"""

idade = float(input('insira sua idade(De 1 a 100):'))
if idade<16:
  print('você não pode votar fi')
elif idade >=16 and idade <18 or idade >=65:
  print('o voto é facultativo papai')
else:
  print('vai votar se não vc vai preso')

"""Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
 “Telefonou para a vítima? “
 “Esteve no local do crime?”
 “Mora perto da vítima? “
 “Devia para a vítima? “
 “Já trabalhou com a vítima? “
O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
Caso contrário, ele será classificado como “Inocente“.

"""

print('Responda às seguintes perguntas com sim ou não: ')

pergunta1 = str(input('Telefonou para a vitima?')).lower()
pergunta2 = str(input('Esteve no local do crime?')).lower()
pergunta3 = str(input('Mora perto da vítima?')).lower()
pergunta4 = str(input('Devia para a vítima?')).lower()
pergunta5 = str(input('Já trabalhou com a vítima?')).lower()

positivas = 0

if pergunta1 == 'sim':
  positivas += 1
if pergunta2 == 'sim':
  positivas += 1
if pergunta3 == 'sim':
  positivas += 1
if pergunta4 == 'sim':
  positivas += 1
if pergunta5 == 'sim':
  positivas += 1

if positivas == 2:
  print('Suspeito')
if positivas >=3 and positivas <=4 :
  print('Cúmplice')
if positivas == 5:
  print('assasino')
if positivas <=1 or positivas <=0:
  print('inocente')

"""Faça um programa que pergunte o preço de três produtos e informe qual produto
você deve comprar, sabendo que a decisão é sempre pelo mais barato.
"""

valor1 = float(input('insira o valor 1 '))
valor2 = float(input('insira o valor 2 '))
valor3 = float(input('insira o valor 3 '))

if valor1 < valor2 and valor2 <valor3:
  print('o primeiro produto é melhor')
if valor2 < valor1 and valor1 <valor3:
  print('o segundo produto é melhor')
else:
  print('o terceiro é melhor')